const LINE_LOGIN_CHANNEL_ID = '';

const LINE_LOGIN_CHANNEL_SECRET = '';

const LINE_LOGIN_CALLBACK_URL= '';

const API_KEY = '513ef696-355b-4018-b3d8-58f4ef4741a7';

const API_SECRET_KEY = '1dadaa73-608c-4cd2-93b5-62fbb7ca6438';

const WALLET_NAME = 'ZeroWasterWallet';

const WALLET_SECRET_KEY = 'pTYzfe/e7ysFJ1g8wrvcJjZ3xNTYD6gG0IYRtI5I6z0=';

const WALLET_ADDRESS = 'tlink12v8lvkrtfes48gy9mmykcjte0wch43r8rx5dj4';

const MY_USER_ID = 'U086c14ab26a49c942f809c0c12349747';

const MY_ADDRESS = 'tlink1a8gqm3avaytsanwka07362y2h28l6fxtssgevt';

const SERVER_IP = '18.214.194.190';

const LINE_SERVER_URL = 'https://test-api.blockchain.line.me';
// Non Fungible Token
const MAOKAI_NFT_TOKEN_CONTRACT_ID = '85e2f1cd'

const MAOKAI_NFT_TOKEN_TYPE = '10000001'

const MALPHITE_NFT_TOKEN_CONTRACT_ID = '85e2f1cd';

const MALPHITE_NFT_TOKEN_TYPE = '10000002';

const IVERN_NFT_TOKEN_CONTRACT_ID = '85e2f1cd';

const IVERN_NFT_TOKEN_TYPE = '10000003';

// Service Token
const ECO_TOKEN_CONTRACT_ID = 'c18c5ed6';

const ECO_TOKEN_NAME = 'EcosystemToken';


export {
    LINE_LOGIN_CHANNEL_ID,
    LINE_LOGIN_CHANNEL_SECRET,
    LINE_LOGIN_CALLBACK_URL,
    API_KEY,
    LINE_SERVER_URL,
    API_SECRET_KEY,
    WALLET_NAME,
    WALLET_SECRET_KEY,
    WALLET_ADDRESS,
    SERVER_IP,
    MY_USER_ID,
    MY_ADDRESS,
    MAOKAI_NFT_TOKEN_CONTRACT_ID,
    MAOKAI_NFT_TOKEN_TYPE,
    ECO_TOKEN_CONTRACT_ID,
    MALPHITE_NFT_TOKEN_CONTRACT_ID,
    MALPHITE_NFT_TOKEN_TYPE,
    IVERN_NFT_TOKEN_CONTRACT_ID,
    IVERN_NFT_TOKEN_TYPE
}
